const xml = require('xml');

PORT = 3124;
RESPONSE_HEADERS = [
  'Accept-Patch',
  'Accept-Ranges',
  'Access-Control-Allow-Credentials',
  'Access-Control-Allow-Headers',
  'Access-Control-Allow-Methods',
  'Access-Control-Allow-Origin',
  'Access-Control-Expose-Headers',
  'Access-Control-Max-Age',
  'Age',
  'Allow',
  'Alt-Svc',
  'Cache-Control',
  'Connection',
  'Content-Disposition',
  'Content-Encoding',
  'Content-Language',
  'Content-Length',
  'Content-Location',
  'Content-MD5',
  'Content-Range',
  'Content-Security-Policy',
  'Content-Type',
  'Date',
  'Delta-Base',
  'ETag',
  'Expires',
  'IM',
  'Last-Modified',
  'Link',
  'Location',
  'P3P',
  'Pragma',
  'Proxy-Authenticate',
  'Public-Key-Pins',
  'Refresh',
  'Retry-After',
  'Server',
  'Set-Cookie',
  'Status',
  'Strict-Transport-Security',
  'Timing-Allow-Origin',
  'Tk',
  'Trailer',
  'Transfer-Encoding',
  'Upgrade',
  'Vary',
  'Via',
  'Warning',
  'WWW-Authenticate',
  'X-Content-Duration',
  'X-Content-Security-Policy',
  'X-Content-Type-Options',
  'X-Correlation-ID',
  'X-Frame-Options',
  'X-Powered-By',
  'X-Request-ID',
  'X-UA-Compatible',
  'X-WebKit-CSP',
  'X-XSS-Protection'
];
XML_DEFAULT_RESPONSE_BODY = xml([ { toys: [ { _attr: { decade: '80s', locale: 'US'} }, { toy: 'Transformers' } , { toy: 'GI Joe' }, { toy: 'He-man' } ] } ]);
JSON_DEFAULT_RESPONSE_BODY = {
  "name": "Bob",
  "age": 34,
  "children": [
    { "name": "Jan", "age": 6 },
    { "name": "Ben", "age": 2 }
  ]
};
